name:                graphql2python
version:             0.1.0.0
github:              "githubuser/graphql2python"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/graphql2python#readme>

dependencies:
- base >= 4.7 && < 5
- protolude
- attoparsec
- text
- aeson
- scientific
- containers
- unordered-containers
- vector
- template-haskell
- th-lift-instances
- filepath
- prettyprinter
- bytestring
- text-builder
- hedgehog
- regex-tdfa >= 1.2

default-extensions:
- NoImplicitPrelude

library:
  source-dirs: src

ghc-options: -O2
             -Wall
             -Wcompat
             -Wincomplete-record-updates
             -Wincomplete-uni-patterns

executables:
  graphql2python-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options: -O2
                 -Wall
                 -Wcompat
                 -Wincomplete-record-updates
                 -Wincomplete-uni-patterns
    dependencies:
    - graphql2python
    - base >= 4.7 && < 5
    - protolude
    - attoparsec
    - text
    - aeson
    - scientific
    - containers
    - unordered-containers
    - vector
    - template-haskell
    - th-lift-instances
    - filepath
    - prettyprinter
    - bytestring
    - text-builder
    - hedgehog
    - regex-tdfa >= 1.2

tests:
  graphql2python-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graphql2python
